-- Users table seeds here (Example)
INSERT INTO users (name) VALUES ('Alice');
INSERT INTO users (name) VALUES ('Kira');
INSERT INTO users (name) VALUES ('Kay');
INSERT INTO users (name) VALUES ('Jay');
INSERT INTO users (name) VALUES ('Bob');
INSERT INTO users (name) VALUES ('Carol');
INSERT INTO users (name) VALUES ('Derek');
INSERT INTO users (name) VALUES ('Pikachu');
INSERT INTO users (name) VALUES ('Bulbasaur');
INSERT INTO users (name) VALUES ('Ivysaur');
INSERT INTO users (name) VALUES ('Venusaur');
INSERT INTO users (name) VALUES ('Charmander');
INSERT INTO users (name) VALUES ('Charizard');
